name: ESlint Linting Process

on: [pull_request, push]

env:
  DATABASE_URL: "CI_FAKE_URL"
  NEXTAUTH_URL: "CI_FAKE_URL"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
