name: Jest Unit Testing

on: [pull_request, push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm test
